### ISSUE TITLE
CI for coding productivity for your project my universe

### ISSUE THREAD

**Issue by yungyuc** [chrisPyr/My_Universe#1]
I see you have automatic tests set up: https://github.com/chrisPyr/My_Universe/blob/902505f9a8701255f8fa9d630263635823f09aef/test_system.py#L10

It may further speed up your coding by setting up CI.

**Comment by chrisPyr** [comment]
@yungyuc 
I've set up the github action:
https://github.com/chrisPyr/My_Universe/blob/4fb9d74f736b938c5180efe8e92439de107e08cd/.github/workflows/test.yml#L1

**Comment by yungyuc** [comment]
LGTM.  Hope you like it.
